import { useMemo } from 'react';
import type { LensType, LensGraphData, LensNode, LensEdge, LensEdgeData } from '../types';
import { computeTopologyLayout } from '../layouts/topology-layout';
import { computeTreeLayout } from '../layouts/tree-layout';
import { computeBridgeLayout } from '../layouts/bridge-layout';
import { computeTimelineLayout } from '../layouts/timeline-layout';

type RawEdge = LensGraphData['edges'][number];

/** Filter and cap topology edges: keep weight >= 0.4, cap at 1.5x node count, highest weight first */
function filterTopologyEdges(edges: RawEdge[], nodeCount: number): RawEdge[] {
	const sorted = [...edges].sort((a, b) => (b.weight ?? 0.5) - (a.weight ?? 0.5));
	const aboveThreshold = sorted.filter((e) => (e.weight ?? 0.5) >= 0.4);
	const cap = Math.ceil(1.5 * nodeCount);
	return aboveThreshold.slice(0, cap);
}

export function useLensLayout(graphData: LensGraphData | null, lens: LensType) {
	return useMemo(() => {
		if (!graphData || graphData.nodes.length === 0) {
			return { nodes: [] as LensNode[], edges: [] as LensEdge[] };
		}

		let layoutResult: { positions: Map<string, { x: number; y: number }>; [key: string]: unknown };
		let filteredEdges: RawEdge[];

		switch (lens) {
			case 'thinking-tree':
				filteredEdges = graphData.edges;
				layoutResult = computeTreeLayout({
					nodes: graphData.nodes,
					edges: filteredEdges,
				});
				break;
			case 'bridge':
				filteredEdges = graphData.edges.filter((e) => e.kind === 'cross-domain');
				layoutResult = computeBridgeLayout({
					nodes: graphData.nodes,
					edges: filteredEdges,
					clusters: graphData.clusters,
					bridges: graphData.bridges,
				});
				break;
			case 'timeline':
				filteredEdges = graphData.edges.filter((e) => e.kind === 'temporal');
				layoutResult = computeTimelineLayout({
					nodes: graphData.nodes,
					evolutionChains: graphData.evolutionChains,
				});
				break;
			case 'topology':
			default:
				filteredEdges = filterTopologyEdges(graphData.edges, graphData.nodes.length);
				layoutResult = computeTopologyLayout({
					nodes: graphData.nodes,
					edges: filteredEdges,
				});
				break;
		}

		const nodes: LensNode[] = graphData.nodes.map((n) => ({
			id: n.path,
			type: 'lensNode' as const,
			position: layoutResult.positions.get(n.path) ?? { x: 0, y: 0 },
			data: n,
		}));

		const edges: LensEdge[] = filteredEdges.map((e, i) => ({
			id: `e-${i}-${e.source}-${e.target}`,
			source: e.source,
			target: e.target,
			type: 'lensEdge',
			data: { kind: e.kind, weight: e.weight },
		}));

		// Merge extra edges generated by layout algorithms
		const extraEdges: LensEdge[] = [];
		if (lens === 'bridge' && 'bridgeEdges' in layoutResult && Array.isArray(layoutResult.bridgeEdges)) {
			for (const e of layoutResult.bridgeEdges as Array<{ source: string; target: string; kind: string; label?: string }>) {
				extraEdges.push({
					id: `bridge-${e.source}-${e.target}`,
					source: e.source,
					target: e.target,
					type: 'lensEdge',
					data: { kind: e.kind as LensEdgeData['kind'], edgeLabel: e.label },
				});
			}
		}
		if (lens === 'timeline' && 'chainEdges' in layoutResult && Array.isArray(layoutResult.chainEdges)) {
			for (const e of layoutResult.chainEdges as Array<{ source: string; target: string; kind: string; chainIndex: number }>) {
				extraEdges.push({
					id: `chain-${e.chainIndex}-${e.source}-${e.target}`,
					source: e.source,
					target: e.target,
					type: 'lensEdge',
					data: { kind: e.kind as LensEdgeData['kind'] },
				});
			}
		}

		return { nodes, edges: [...edges, ...extraEdges] };
	}, [graphData, lens]);
}
