import { useMemo } from 'react';
import type { LensType, LensGraphData, LensNode, LensEdge } from '../types';
import { computeTopologyLayout } from '../layouts/topology-layout';
import { computeTreeLayout } from '../layouts/tree-layout';
import { computeBridgeLayout } from '../layouts/bridge-layout';
import { computeTimelineLayout } from '../layouts/timeline-layout';

export function useLensLayout(graphData: LensGraphData | null, lens: LensType) {
	return useMemo(() => {
		if (!graphData || graphData.nodes.length === 0) {
			return { nodes: [] as LensNode[], edges: [] as LensEdge[] };
		}

		let layoutResult: { positions: Map<string, { x: number; y: number }>; [key: string]: unknown };

		switch (lens) {
			case 'thinking-tree':
				layoutResult = computeTreeLayout({
					nodes: graphData.nodes,
					edges: graphData.edges,
				});
				break;
			case 'bridge':
				layoutResult = computeBridgeLayout({
					nodes: graphData.nodes,
					edges: graphData.edges,
					clusters: graphData.clusters,
					bridges: graphData.bridges,
				});
				break;
			case 'timeline':
				layoutResult = computeTimelineLayout({
					nodes: graphData.nodes,
					evolutionChains: graphData.evolutionChains,
				});
				break;
			case 'topology':
			default:
				layoutResult = computeTopologyLayout({
					nodes: graphData.nodes,
					edges: graphData.edges,
				});
				break;
		}

		const nodes: LensNode[] = graphData.nodes.map((n) => ({
			id: n.path,
			type: 'lensNode' as const,
			position: layoutResult.positions.get(n.path) ?? { x: 0, y: 0 },
			data: n,
		}));

		const edges: LensEdge[] = graphData.edges.map((e, i) => ({
			id: `e-${i}-${e.source}-${e.target}`,
			source: e.source,
			target: e.target,
			type: 'lensEdge',
			data: { kind: e.kind, weight: e.weight },
		}));

		// Merge extra edges generated by layout algorithms
		const extraEdges: LensEdge[] = [];
		if ('bridgeEdges' in layoutResult && Array.isArray(layoutResult.bridgeEdges)) {
			for (const e of layoutResult.bridgeEdges as Array<{ source: string; target: string; kind: string; label?: string }>) {
				extraEdges.push({
					id: `bridge-${e.source}-${e.target}`,
					source: e.source,
					target: e.target,
					type: 'lensEdge',
					data: { kind: e.kind as LensEdge['data']['kind'], edgeLabel: e.label },
				});
			}
		}
		if ('chainEdges' in layoutResult && Array.isArray(layoutResult.chainEdges)) {
			for (const e of layoutResult.chainEdges as Array<{ source: string; target: string; kind: string; chainIndex: number }>) {
				extraEdges.push({
					id: `chain-${e.chainIndex}-${e.source}-${e.target}`,
					source: e.source,
					target: e.target,
					type: 'lensEdge',
					data: { kind: e.kind as LensEdge['data']['kind'] },
				});
			}
		}

		return { nodes, edges: [...edges, ...extraEdges] };
	}, [graphData, lens]);
}
