import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import alias from "esbuild-plugin-alias";
import path from "path";
import { fileURLToPath } from "url";
import fs from "fs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

/** Keep in sync with `SLICE_CAPS.build.esbuildLogInputs` in `src/core/constant.ts` (Node cannot import TS here). */
const ESBUILD_LOG_TOP_INPUTS = 50;

/**
 * After bundle is written, patch main.js so Error.__BluebirdErrorTypes__ is configurable: true.
 * Bluebird sets it configurable: false so we cannot delete it at runtime; we have code control so we fix it at build time.
 */
const bluebirdConfigurablePlugin = {
	name: 'bluebird-configurable',
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length) return;
			const outPath = path.join(__dirname, 'main.js');
			try {
				const content = await fs.promises.readFile(outPath, 'utf8');
				// Match both dev (configurable: false) and prod minified (configurable:!1)
				const patched = content.replace(
					/(Error,\s*["']__BluebirdErrorTypes__["'][^)]*?)configurable:\s*(?:false|!1)/g,
					'$1configurable: true'
				);
				if (patched !== content) {
					await fs.promises.writeFile(outPath, patched, 'utf8');
					console.log('[bluebird-configurable] Patched __BluebirdErrorTypes__ to configurable: true in main.js');
				}
			} catch (e) {
				console.warn('[bluebird-configurable] Patch failed:', e?.message);
			}
		});
	},
};

/**
 * Plugin to fix createRequire(import.meta.url) issues in bundled code
 * Some packages like @langchain/community use createRequire(import.meta.url)
 * In CommonJS output, we can use __filename directly instead
 */
const fixImportMetaPlugin = {
	name: 'fix-import-meta',
	setup(build) {
		build.onLoad({ filter: /node_modules\/@langchain\/community\/.*\.(js|mjs|cjs)$/ }, async (args) => {
			try {
				const contents = await fs.promises.readFile(args.path, 'utf8');
				
				// Fix createRequire(import.meta.url) patterns
				// In CommonJS, __filename is available, so we can use it directly
				let modified = contents;
				
				// Pattern: createRequire(import.meta.url)
				// Replace with createRequire(__filename) for CommonJS
				if (contents.includes('createRequire(import.meta.url)')) {
					modified = modified.replace(
						/createRequire\(import\.meta\.url\)/g,
						'(function() { const { createRequire } = require("module"); return createRequire(typeof __filename !== "undefined" ? __filename : require("path").join(__dirname, "index.js")); })()'
					);
				}
				
				// Pattern: createRequire(import.meta.url || ...)
				if (contents.includes('createRequire(import.meta.url')) {
					modified = modified.replace(
						/createRequire\(import\.meta\.url(?:\s*\|\|.*?)?\)/g,
						'(function() { const { createRequire } = require("module"); return createRequire(typeof __filename !== "undefined" ? __filename : require("path").join(__dirname, "index.js")); })()'
					);
				}

				if (modified !== contents) {
					return {
						contents: modified,
						loader: 'js',
					};
				}
			} catch (error) {
				// If we can't read/modify the file, just return undefined to use default handling
				console.warn(`[fix-import-meta] Could not process ${args.path}:`, error.message);
			}
		});
	},
};

const shared = {
	banner: { js: banner },
	bundle: true,
	platform: "node",
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
	plugins: [
		alias({
			"@": path.resolve(__dirname, "src"),
			"lucide-react": path.resolve(__dirname, "node_modules/lucide-react/dist/cjs/lucide-react.js"),
		}),
		fixImportMetaPlugin,
		bluebirdConfigurablePlugin,
	],
	external: [
		"obsidian",
		"electron",
		"better-sqlite3", // Mark as external so it loads from node_modules (native module)
		"pdfjs-dist", // Heavy lib: load at runtime to keep main.js small; worker loaded via GlobalWorkerOptions.workerSrc (CDN)
		// NOTE: @anthropic-ai/claude-agent-sdk is INLINED into main.js (not external).
		// Its sdk.mjs is ESM-only; Obsidian's Electron/Node cannot runtime-require it.
		// The SDK's cli.js (Claude Code runtime) is kept as a sidecar in sdk/cli.js
		// and spawned as a subprocess via explicit options.pathToClaudeCodeExecutable
		// at every query() call, so the SDK's auto-resolve code path (which uses
		// import.meta.url to find cli.js) is never executed at runtime.
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"playwright",
		"playwright-core",
		"chromium-bidi",
		...builtins,
	],
	loader: {
		".woff": "empty",
		".woff2": "empty",
		".ttf": "empty",
		".eot": "empty",
	},
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	// Always strip bundled license comments: nested `*/` inside dependency license text can terminate
	// the outer `/*! … */` block early and leave invalid JS (Obsidian eval: SyntaxError). Same as prod.
	legalComments: "none",
	treeShaking: true,
	// Always minify: @shikijs/langs ships grammar as JSON.parse('…') in a form that can produce
	// invalid JavaScript when esbuild emits unminified output (Obsidian eval fails: SyntaxError).
	keepNames: !prod,
	minify: true,
};

const mainContext = await esbuild.context({
	...shared,
	entryPoints: ["main.ts"],
	format: "cjs",
	outfile: "main.js",
	metafile: true,
});

if (prod) {
	const result = await mainContext.rebuild();
	if (process.env.BUNDLE_METAFILE && result.metafile) {
		const outputs = result.metafile.outputs;
		const outEntry = Object.keys(outputs)[0];
		const outMeta = outEntry && outputs[outEntry];
		if (outMeta) {
			const inputs = Object.entries(result.metafile.inputs)
				.map(([k, b]) => [k.replace(__dirname + path.sep, ""), b.bytes])
				.sort((a, b) => b[1] - a[1]);
			console.log("\n[Bundle] Total:", (outMeta.bytes / 1024 / 1024).toFixed(2), "MB");
			console.log("[Bundle] Top 50 inputs by size:");
			inputs.slice(0, ESBUILD_LOG_TOP_INPUTS).forEach(([k, b], i) =>
				console.log(" ", (i + 1) + ".", (b / 1024).toFixed(1) + " KB", k)
			);
		}
	}
	process.exit(0);
} else {
	await mainContext.watch();
}
