/**
 * Image summary prompt.
 * Summarizes image descriptions generated by vision models.
 */
export const template = `Summarize this image description concisely (200-500 characters).

{{#if title}}
Title: {{title}}
{{/if}}

{{#if path}}
Path: {{path}}
{{/if}}

Image Description:
{{content}}

Provide a concise summary focusing on the key visual elements, objects, and scene described.`;

export const expectsJson = false;

