import { LLMUsage, mergeTokenUsage } from "@/core/providers/types";
import { refreshableMemoizeSupplier, Supplier } from "@/core/utils/functions";
import { AIServiceManager } from "@/service/chat/service-manager";
import { searchMemoryStoreInputSchema } from "@/core/schemas/tools/searchMemoryStore";
import { AISearchSource, AISearchTopic, DashboardBlock, SearchAgentResult, type EvidenceIndex } from "../AISearchAgent";
import { AgentTool, safeAgentTool } from "@/service/tools/types";
import { contentReaderTool } from "@/service/tools/content-reader";
import type {
    DimensionChoice,
    EvidenceTaskGroup,
    EvidencePack,
    RawSearchReportWithDimension,
    ConsolidatorOutput,
    ReportPlan,
    ReportVisualBlueprint
} from "@/core/schemas/agents/search-agent-schemas";
import type { ReportBlockBlueprintItem } from "./helpers/report-block-plan-weaver";

/** User persona from classifier (appeal + detail_level). Used by report phases for style. */
export interface UserPersonaConfig {
    appeal?: string;
    detail_level?: string;
}
/** Stage names for searchHistory query (stage:). Content is built from structured fields, not a separate history log. */
export const ANALYSIS_HISTORY_STAGES = [
    'Classify',
    'Dimensions',
    'Recon',
    'Consolidator',
    'EvidenceGroups',
    'Evidence',
] as const;

/** Serializable snapshot of search memory for debug (window.__peakSearchDebug). */
export interface SearchMemoryDebugSnapshot {
    initialPromptPreview: string;
    totalTokenUsage: LLMUsage;
    agentResult: {
        title: string;
        summaryLength: number;
        topicsCount: number;
        sourcesCount: number;
        dashboardBlocksCount: number;
        suggestedFollowUpQuestionsCount: number;
    };
    verifiedPaths: string[];
    dossier: {
        verifiedPathsCount: number;
        sourcePathsSample: string[];
    };
    /** Recall pipeline: dimensions (after classify), evidenceGroups (after recon), evidencePacks (final). */
    recallPipeline?: {
        dimensionsCount: number;
        evidenceGroupsCount: number;
        evidencePacksCount: number;
    };
}

const DEFAULT_GREP_MAX_MATCHES = 50;

export type AgentMemoryToolSet = {
    search_analysis_context: AgentTool;
    /** Read full content of a path from Source Map / verified paths when session context is incomplete. */
    content_reader: AgentTool;
};

function escapeRegExpLiteral(input: string): string {
    return input.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function buildAutoRegex(query: string, caseSensitive: boolean): { regex: RegExp; isLiteralFallback: boolean } {
    const flags = caseSensitive ? 'g' : 'gi';
    try {
        return { regex: new RegExp(query, flags), isLiteralFallback: false };
    } catch {
        return { regex: new RegExp(escapeRegExpLiteral(query), flags), isLiteralFallback: true };
    }
}

/**
 * Manages agent memory and session summarization.
 * Uses getModelForPrompt(AiAnalysisSessionSummary) for summarization model.
 */
export class AgentContextManager {

    /** Initial prompt. */
    private initialPrompt: string = '';

    /** Verified paths (exist in vault/DB or appeared in tool outputs). */
    private verifiedPaths: Set<string> = new Set();

    /** 
     * Recall pipeline snapshot: dimensions after classify, 
     */
    private recallDimensions: DimensionChoice[] = [];
    /** 
     * After Classify before Recon. User persona from classifier (appeal, detail_level). Persisted after classify for report phases. 
     */
    private userPersonaConfig: UserPersonaConfig | null = null;
    /** 
     * After Recon before Evidence. Recon reports per dimension (persisted after batchStreamRecon for dossier/finish). 
     */
    private reconReports: RawSearchReportWithDimension[] = [];
    /** 
     * After Recon before Evidence. Consolidator output (persisted after streamTaskConsolidator for dossier/finish). 
     */
    private consolidatorOutput: ConsolidatorOutput | null = null;
    /** 
     * Recall pipeline snapshot: evidenceGroups after recon. 
     */
    private recallEvidenceTaskGroups: EvidenceTaskGroup[] = [];
    /** 
     * Recall pipeline snapshot: then final evidencePacks. 
     */
    private recallEvidencePacks: EvidencePack[] = [];

    /**
     * Report pipeline snapshot: Overview diagram generated by Mermaid Overview Agent (raw Mermaid code).
     */
    private mermaidOverviewFromEvidenceWeaved?: string;
    /** 
     * Report pipeline snapshot: Executable report outline from ReportPlanAgent (body/appendices/actions/sources specs). 
     */
    private reportPlan?: ReportPlan;
    /** 
     * Report pipeline snapshot: Follow-up questions suggested by a dedicated agent from full search history/session; not from topics. 
     */
    private suggestedFollowUpQuestions?: string[];
    /** 
     * Report pipeline snapshot: Per-block visual prescriptions from VisualBlueprintAgent (after report plan). 
     */
    private reportVisualBlueprint?: ReportVisualBlueprint;
    /**
     * Report pipeline snapshot: Final per-block generation blueprint (already weaved from report plan + visual blueprint).
     * Stored as structured items; rendered to strings only when calling DashboardBlocksAgent.
     */
    private reportBlockBlueprintItems?: ReportBlockBlueprintItem[];

    /** 
     * Report pipeline snapshot: Topics from search agent (after report plan). 
     */
    private topics: AISearchTopic[] = [];
    /** 
     * Report pipeline snapshot: Sources from search agent (after report plan). 
     */
    private sources: AISearchSource[] = [];
    /** 
     * Report pipeline snapshot: Dashboard blocks from dashboard blocks agent (after report plan). 
     */
    private dashboardBlocks: DashboardBlock[] = [];
    /** 
     * Report pipeline snapshot: Summary from summary agent (after report plan). 
     */
    private summary: string = '';

    /** Report pipeline: short display title (e.g. for save filename, recent list). */
    private title: string = '';

    private totalTokenUsage: LLMUsage = { inputTokens: 0, outputTokens: 0, totalTokens: 0 };

    constructor(
        private readonly aiServiceManager: AIServiceManager,
    ) { }

    public resetAgentMemory(initialPrompt: string): void {
        this.initialPrompt = initialPrompt ?? '';
        this.totalTokenUsage = { inputTokens: 0, outputTokens: 0, totalTokens: 0 };
        this.title = '';
        this.summary = '';
        this.topics = [];
        this.sources = [];
        this.dashboardBlocks = [];
        this.suggestedFollowUpQuestions = undefined;
        this.mermaidOverviewFromEvidenceWeaved = undefined;
        this.reportPlan = undefined;
        this.reportVisualBlueprint = undefined;
        this.reportBlockBlueprintItems = undefined;
        this.verifiedPaths.clear();
        this.recallDimensions = [];
        this.recallEvidenceTaskGroups = [];
        this.recallEvidencePacks = [];
        this.reconReports = [];
        this.consolidatorOutput = null;
        this.userPersonaConfig = null;
    }

    /** Report pipeline: title (used for save filename, recent list). */
    public getTitle(): string {
        return this.title ?? '';
    }

    public setTitle(value: string | undefined): void {
        this.title = (value ?? '').trim() || '';
    }

    public getSummary(): string {
        return this.summary ?? '';
    }

    public setSummary(value: string): void {
        this.summary = value ?? '';
    }

    public getTopics(): AISearchTopic[] {
        return this.topics ?? [];
    }

    public setTopics(value: AISearchTopic[]): void {
        this.topics = value ?? [];
    }

    public getSources(): AISearchSource[] {
        return this.sources ?? [];
    }

    public setSources(value: AISearchSource[]): void {
        this.sources = value ?? [];
    }

    public getDashboardBlocks(): DashboardBlock[] {
        return this.dashboardBlocks ?? [];
    }

    public setDashboardBlocks(value: DashboardBlock[]): void {
        this.dashboardBlocks = value ?? [];
    }

    public getSuggestedFollowUpQuestions(): string[] {
        return this.suggestedFollowUpQuestions ?? [];
    }

    public setSuggestedFollowUpQuestions(value: string[] | undefined): void {
        this.suggestedFollowUpQuestions = value ?? undefined;
    }

    public getEvidenceWeavedMermaidOverview(): string {
        return (this.mermaidOverviewFromEvidenceWeaved ?? '').trim();
    }

    public setEvidenceWeavedMermaidOverviewAgent(value: string | undefined): void {
        this.mermaidOverviewFromEvidenceWeaved = value;
    }

    public getReportPlan(): ReportPlan | undefined {
        return this.reportPlan;
    }

    public setReportPlan(value: ReportPlan | undefined): void {
        this.reportPlan = value;
    }

    /**
     * Build a compact markdown "plan" so Summary can preview the report structure
     * and reference blocks naturally via #block-<id> anchors.
     *
     * Prefers ReportPlan (body/appendices specs). Falls back to current dashboard blocks.
     */
    public buildDashboardBlockPlanMarkdown(): string | undefined {
        const plan = this.reportPlan;
        const blocks = this.dashboardBlocks ?? [];
        const lines: string[] = [];

        if (plan && ((plan.bodyBlocksSpec?.length ?? 0) > 0 || (plan.appendicesBlocksSpec?.length ?? 0) > 0)) {
            lines.push('Body blocks:');
            for (const b of plan.bodyBlocksSpec ?? []) {
                const parts: string[] = [];
                parts.push(`- [${b.title}](#block-${b.blockId}) (id: ${b.blockId}; role: ${b.role}${b.wordTarget ? `; target: ~${b.wordTarget}w` : ''})`);
                if (b.paragraphSkeleton) parts.push(`  - skeleton: ${b.paragraphSkeleton}`);
                if (b.evidenceBinding) parts.push(`  - evidence: ${b.evidenceBinding}`);
                if (b.risksUncertaintyHint) parts.push(`  - uncertainty: ${b.risksUncertaintyHint}`);
                lines.push(...parts);
            }
            if ((plan.appendicesBlocksSpec?.length ?? 0) > 0) {
                lines.push('', 'Appendices blocks:');
                for (const a of plan.appendicesBlocksSpec ?? []) {
                    const parts: string[] = [];
                    parts.push(`- [${a.title}](#block-${a.blockId}) (id: ${a.blockId}; role: ${a.role})`);
                    if (a.contentHint) parts.push(`  - hint: ${a.contentHint}`);
                    lines.push(...parts);
                }
            }
        } else if (blocks.length > 0) {
            lines.push('Current blocks:');
            for (const b of blocks) {
                const id = (b.id ?? '').trim();
                if (!id) continue;
                const title = (b.title ?? '').trim() || '(untitled)';
                const engine = (b.renderEngine ?? 'MARKDOWN').toUpperCase();
                lines.push(`- [${title}](#block-${id}) (id: ${id}; engine: ${engine})`);
            }
        }

        const text = lines.join('\n').trim();
        return text ? text : undefined;
    }

    public getReportVisualBlueprint(): ReportVisualBlueprint | undefined {
        return this.reportVisualBlueprint;
    }

    public setReportVisualBlueprint(value: ReportVisualBlueprint | undefined): void {
        this.reportVisualBlueprint = value;
    }

    /** Final weaved report block blueprint items (structured; internal report generation only). */
    public getReportBlockBlueprintItems(): ReportBlockBlueprintItem[] {
        return this.reportBlockBlueprintItems ?? [];
    }

    public setReportBlockBlueprintItems(value: ReportBlockBlueprintItem[]): void {
        this.reportBlockBlueprintItems = value ?? [];
    }

    /** Persist user persona from classifier (appeal, detail_level). Used by report phases for style. */
    public setUserPersonaConfig(config: UserPersonaConfig | undefined): void {
        this.userPersonaConfig = config && (config.appeal != null || config.detail_level != null) ? config : null;
    }

    public getUserPersonaConfig(): UserPersonaConfig | null {
        return this.userPersonaConfig;
    }

    /** Persist recon reports (from RawSearchAgent after batchStreamRecon). */
    public setReconReports(reports: RawSearchReportWithDimension[]): void {
        this.reconReports = reports ?? [];
    }

    public getReconReports(): RawSearchReportWithDimension[] {
        return this.reconReports;
    }

    /** Persist consolidator output (from RawSearchAgent after streamTaskConsolidator). */
    public setConsolidatorOutput(out: ConsolidatorOutput | null): void {
        this.consolidatorOutput = out ?? null;
    }

    public getConsolidatorOutput(): ConsolidatorOutput | null {
        return this.consolidatorOutput;
    }

    /** Set dimensions extracted after classify (for recall pipeline snapshot). */
    public setRecallDimensions(dimensions: DimensionChoice[]): void {
        this.recallDimensions = dimensions ?? [];
    }

    /** Set evidence groups after recon + grouping (for recall pipeline snapshot). */
    public setRecallEvidenceTaskGroups(groups: EvidenceTaskGroup[]): void {
        this.recallEvidenceTaskGroups = groups ?? [];
    }

    /** Set final evidence packs after evidence phase (for recall pipeline snapshot). */
    public setRecallEvidencePacks(packs: EvidencePack[]): void {
        this.recallEvidencePacks = packs ?? [];
    }

    public getRecallDimensions(): DimensionChoice[] {
        return this.recallDimensions;
    }

    public getRecallEvidenceTaskGroups(): EvidenceTaskGroup[] {
        return this.recallEvidenceTaskGroups;
    }

    public getRecallEvidencePacks(): EvidencePack[] {
        return this.recallEvidencePacks;
    }

    public accumulateTokenUsage(usage?: LLMUsage): void {
        if (!usage) return;
        this.totalTokenUsage = mergeTokenUsage(this.totalTokenUsage, usage);
    }

    public getTotalTokenUsage(): LLMUsage {
        return this.totalTokenUsage;
    }

    public getInitialPrompt(): string {
        return this.initialPrompt ?? '';
    }

    public yieldAgentResult(): { extra: { currentResult: SearchAgentResult } } {
        return {
            extra: {
                currentResult: this.getAgentResult(),
            },
        };
    }

    /**
     * Returns a result view so that update-result tools mutate the same arrays (topics, sources, dashboardBlocks).
     * Stream complete / UI still get a snapshot via this object; arrays are live references.
     */
    public getAgentResult(): SearchAgentResult {
        const self = this;
        return {
            get title() {
                return self.title || undefined;
            },
            set title(v: string | undefined) {
                self.setTitle(v);
            },
            get summary() {
                return self.summary ?? '';
            },
            set summary(v: string) {
                self.setSummary(v);
            },
            get topics() {
                return self.topics ?? [];
            },
            set topics(v: AISearchTopic[]) {
                self.setTopics(v ?? []);
            },
            get sources() {
                return self.sources ?? [];
            },
            set sources(v: AISearchSource[]) {
                self.setSources(v ?? []);
            },
            get dashboardBlocks() {
                return self.dashboardBlocks ?? [];
            },
            set dashboardBlocks(v: DashboardBlock[]) {
                self.setDashboardBlocks(v ?? []);
            },
            get suggestedFollowUpQuestions() {
                return self.suggestedFollowUpQuestions;
            },
            set suggestedFollowUpQuestions(v: string[] | undefined) {
                self.setSuggestedFollowUpQuestions(v);
            },
            get evidenceMermaidOverviewAgent() {
                return self.mermaidOverviewFromEvidenceWeaved;
            },
            set evidenceMermaidOverviewAgent(v: string | undefined) {
                self.setEvidenceWeavedMermaidOverviewAgent(v);
            },
            get reportPlan() {
                return self.reportPlan;
            },
            set reportPlan(v: ReportPlan | undefined) {
                self.setReportPlan(v);
            },
            get reportVisualBlueprint() {
                return self.reportVisualBlueprint;
            },
            set reportVisualBlueprint(v: ReportVisualBlueprint | undefined) {
                self.setReportVisualBlueprint(v);
            },
            get evidenceIndex(): EvidenceIndex {
                const packs = self.getRecallEvidencePacks();
                const index: EvidenceIndex = {};
                for (const p of packs) {
                    const path = p.origin?.path_or_url ?? '';
                    if (!path) continue;
                    if (!index[path]) index[path] = { summaries: [], facts: [] };
                    if (p.summary) index[path].summaries.push(p.summary);
                    for (const f of p.facts ?? []) {
                        index[path].facts.push({ claim: f.claim, quote: f.quote });
                    }
                }
                return index;
            },
        };
    }

    public getVerifiedPaths(): Set<string> {
        return this.verifiedPaths;
    }

    public appendVerifiedPaths(paths: string[] | string): void {
        if (!paths) return;
        const arr = typeof paths === 'string' ? [paths] : paths;
        for (const p of arr) {
            const t = p?.trim();
            if (t) this.verifiedPaths.add(t);
        }
    }

    /**
     * Serializable snapshot of current search memory for debug (e.g. window.__peakSearchDebug.getSnapshot()).
     */
    public getDebugSnapshot(): SearchMemoryDebugSnapshot {
        const maxPromptPreview = 300;
        const paths = Array.from(this.verifiedPaths);
        return {
            initialPromptPreview: (this.initialPrompt ?? '').slice(0, maxPromptPreview),
            totalTokenUsage: this.totalTokenUsage ?? { inputTokens: 0, outputTokens: 0, totalTokens: 0 },
            agentResult: {
                title: this.title ?? '',
                summaryLength: (this.summary ?? '').length,
                topicsCount: (this.topics ?? []).length,
                sourcesCount: (this.sources ?? []).length,
                dashboardBlocksCount: (this.dashboardBlocks ?? []).length,
                suggestedFollowUpQuestionsCount: (this.suggestedFollowUpQuestions ?? []).length,
            },
            verifiedPaths: paths,
            dossier: {
                verifiedPathsCount: paths.length,
                sourcePathsSample: paths.slice(0, 30),
            },
            recallPipeline:
                this.recallDimensions.length > 0 ||
                    this.recallEvidenceTaskGroups.length > 0 ||
                    this.recallEvidencePacks.length > 0
                    ? {
                        dimensionsCount: this.recallDimensions.length,
                        evidenceGroupsCount: this.recallEvidenceTaskGroups.length,
                        evidencePacksCount: this.recallEvidencePacks.length,
                    }
                    : undefined,
        };
    }

    /**
     * Verified fact sheet as lines: grouped by pathRef (once per path), then summary line(s), then each claim + quote per line. No snippet.
     * Returns string[] so callers can join or slice as needed.
     */
    public getVerifiedFactSheet(): string[] {
        const packs = this.recallEvidencePacks;
        if (packs.length === 0) return [];

        const maxQuoteLen = 200;
        type PathGroup = { pathRef: string; summaries: string[]; factEntries: Array<{ claim: string; quote: string }> };
        const byPath = new Map<string, PathGroup>();
        const seenClaimsByPath = new Map<string, Set<string>>();

        for (const p of packs) {
            const path = p.origin.path_or_url ?? '';
            const pathRef = path ? `[[${path}]]` : '';
            if (!byPath.has(path)) {
                byPath.set(path, { pathRef, summaries: [], factEntries: [] });
                seenClaimsByPath.set(path, new Set<string>());
            }
            const group = byPath.get(path)!;
            const seenClaims = seenClaimsByPath.get(path)!;

            const summary = (p.summary ?? '').trim();
            if (summary) group.summaries.push(summary);

            for (const f of p.facts ?? []) {
                const claim = (f.claim ?? '').trim();
                const quote = (f.quote ?? '').slice(0, maxQuoteLen);
                const key = claim.slice(0, 80);
                if (!claim || seenClaims.has(key)) continue;
                seenClaims.add(key);
                group.factEntries.push({ claim, quote });
            }
        }

        const lines: string[] = [];
        for (const group of byPath.values()) {
            lines.push(group.pathRef);
            for (const s of group.summaries) lines.push(`  Summary: ${s}`);
            for (const { claim, quote } of group.factEntries) {
                const suffix = quote.length >= maxQuoteLen ? '...' : '';
                lines.push(`  - ${claim}: "${quote}${suffix}"`);
            }
        }
        return lines;
    }

    /** Recon briefing from consolidator + per-dimension tactical summaries. */
    public getReconBriefing(): string {
        const parts: string[] = [];
        const consolidator = this.consolidatorOutput;
        if (consolidator?.global_recon_insight) {
            parts.push('Recon briefing (recon view, not final conclusions):');
            parts.push(consolidator.global_recon_insight.trim());
        }
        const reports = this.reconReports;
        if (reports.length > 0) {
            parts.push('Per-dimension tactical summary:');
            for (const r of reports) {
                const t = (r.tactical_summary ?? '').trim().slice(0, 400);
                if (t) parts.push(`[${r.dimension}] ${t}`);
            }
        }
        return parts.join('\n\n');
    }

    /** Classify section: initial prompt + dimensions chosen (from recall pipeline). */
    private getClassifySectionText(): string {
        const prompt = (this.initialPrompt ?? '').trim();
        const dims = this.recallDimensions;
        const dimLine =
            dims.length > 0
                ? `Dimensions chosen: ${dims.map((d) => `${d.id} (${(d.intent_description ?? '').slice(0, 80)})`).join('; ')}`
                : '';
        return [prompt, dimLine].filter(Boolean).join('\n');
    }

    /** Evidence task group index (paths per group) for prompt context. */
    public getEvidenceGroupIndex(): string {
        const groups = this.recallEvidenceTaskGroups;
        if (groups.length === 0) return '';
        const lines: string[] = ['Evidence task group index (input to evidence phase; paths to read per group):'];
        groups.forEach((eg, i) => {
            const id = eg.groupId ?? `group-${i}`;
            const paths = [...new Set((eg.tasks ?? []).map((t) => t.path).filter(Boolean))];
            const focus = (eg.group_focus ?? '').slice(0, 200);
            const shared = eg.sharedContext ? `\n  sharedContext (excerpt): ${eg.sharedContext.slice(0, 300)}...` : '';
            lines.push(`- ${id} | topic_anchor: ${eg.topic_anchor} | group_focus: ${focus}${shared}\n  paths: ${paths.slice(0, 12).join(', ')}`);
        });
        return lines.join('\n');
    }

    /** Source map: unique paths from evidence packs, or verified paths when no packs. */
    public getSourceMap(): string {
        const packs = this.recallEvidencePacks;
        if (packs.length > 0) {
            return [...new Set(packs.map((p) => p.origin.path_or_url).filter(Boolean))].join('\n');
        }
        return Array.from(this.verifiedPaths).join('\n');
    }

    /** Confirmed facts list derived from evidence packs (summary or first claim per pack). */
    public getConfirmedFacts(): string[] {
        const packs = this.recallEvidencePacks;
        if (packs.length === 0) return [];
        return packs.map((p) => p.summary ?? p.facts[0]?.claim ?? '').filter(Boolean);
    }

    /** Dossier gaps (currently unused; reserved for future). */
    public getDossierGaps(): string[] {
        return [];
    }

    /**
     * Returns full dossier for Summary/Dashboard when multiple fields are needed at once.
     * Prefer individual getters (getVerifiedFactSheet, getReconBriefing, etc.) when only a subset is needed.
     */
    public getDossierForSummary(): {
        verifiedFactSheet: string;
        reconBriefing: string;
        evidenceGroupIndex: string;
        sourceMap: string;
        lastDecision: string;
        confirmedFacts: string[];
        gaps: string[];
        userPersonaConfig?: UserPersonaConfig;
    } {
        return {
            verifiedFactSheet: this.getVerifiedFactSheet().join('\n'),
            reconBriefing: this.getReconBriefing(),
            evidenceGroupIndex: this.getEvidenceGroupIndex(),
            sourceMap: this.getSourceMap(),
            lastDecision: '',
            confirmedFacts: this.getConfirmedFacts(),
            gaps: this.getDossierGaps(),
            userPersonaConfig: this.userPersonaConfig ?? undefined,
        };
    }

    public getAgentMemoryTool(): AgentMemoryToolSet {
        const self = this;
        return {
            search_analysis_context: safeAgentTool({
                description: `Search the structured analysis session. Query: "list" or empty (overview), "stage:<Classify|Dimensions|Recon|Consolidator|EvidenceGroups|Evidence>", "path:<path>", "dimension:<id>", "group:<id>", or free-text keyword. E.g. "stage:Recon", "path:foo.md", or keywords (topic names, file paths).`,
                inputSchema: searchMemoryStoreInputSchema,
                execute: async (input) => {
                    const result = self.searchHistory(input.query, { maxChars: input.maxChars });
                    return { content: result };
                },
            }),
            content_reader: contentReaderTool(),
        }
    }

    /**
     * Single section text for a stage, optionally filtered by path/dimension/group.
     * Used by fullMemoryTextSupplier and searchHistory.
     */
    private getSectionText(
        stage: string,
        filters: { path?: string; dimension?: string; group?: string }
    ): string {
        const pathLower = filters.path?.toLowerCase() ?? '';
        const dim = filters.dimension ?? '';
        const groupId = filters.group ?? '';

        switch (stage) {
            case 'Classify': {
                const raw = this.getClassifySectionText();
                if (dim && this.recallDimensions.some((d) => d.id === dim)) {
                    const d = this.recallDimensions.find((d) => d.id === dim)!;
                    return `${d.id}: ${d.intent_description ?? ''}`;
                }
                return raw;
            }
            case 'Dimensions': {
                const lines = this.recallDimensions.map((d) => `${d.id}: ${d.intent_description ?? ''}`);
                if (dim) return lines.filter((l) => l.startsWith(dim + ':')).join('\n') || '';
                return lines.join('\n');
            }
            case 'Recon': {
                const reports = this.reconReports;
                if (reports.length === 0) return '';
                let out = reports;
                if (dim) out = out.filter((r) => r.dimension === dim);
                if (pathLower) out = out.filter((r) => (r.discovered_leads ?? []).some((p) => p.toLowerCase().includes(pathLower)));
                if (out.length === 0) return '';
                return out.map((r) => `[${r.dimension}] ${(r.tactical_summary ?? '').trim().slice(0, 400)}`).join('\n');
            }
            case 'Consolidator': {
                const c = this.consolidatorOutput;
                if (!c) return '';
                const tasks = (c.consolidated_tasks ?? []).filter((t) => {
                    if (pathLower && !t.path.toLowerCase().includes(pathLower)) return false;
                    if (dim && !(t.relevant_dimension_ids ?? []).some((d) => (d as { id?: string }).id === dim)) return false;
                    return true;
                });
                const insight = pathLower || dim ? '' : (c.global_recon_insight ?? '').trim();
                const taskLines = tasks.slice(0, 30).map((t) => `${t.path}: ${(t.extraction_focus ?? '').slice(0, 120)}`);
                return [insight, ...taskLines].filter(Boolean).join('\n');
            }
            case 'EvidenceGroups': {
                const groups = this.recallEvidenceTaskGroups;
                if (groups.length === 0) return '';
                let gs = groups;
                if (groupId) gs = gs.filter((eg) => (eg.groupId ?? '').includes(groupId) || groups.indexOf(eg) === parseInt(groupId, 10));
                if (pathLower) gs = gs.filter((eg) => (eg.tasks ?? []).some((t) => (t.path ?? '').toLowerCase().includes(pathLower)));
                if (gs.length === 0) return '';
                return gs.map((eg, i) => {
                    const id = eg.groupId ?? `group-${i}`;
                    const paths = [...new Set((eg.tasks ?? []).map((t) => t.path).filter(Boolean))];
                    return `${id} | ${eg.topic_anchor} | ${(eg.group_focus ?? '').slice(0, 200)}\n  paths: ${paths.slice(0, 12).join(', ')}`;
                }).join('\n');
            }
            case 'Evidence': {
                const lines = this.getVerifiedFactSheet();
                if (lines.length === 0) return '';
                if (pathLower) {
                    const result: string[] = [];
                    let inBlock = false;
                    for (const l of lines) {
                        if (l.startsWith('[[') && l.toLowerCase().includes(pathLower)) inBlock = true;
                        if (inBlock) result.push(l);
                        if (inBlock && l.startsWith('[[') && !l.toLowerCase().includes(pathLower)) inBlock = false;
                    }
                    return result.length > 0 ? result.join('\n') : lines.filter((l) => l.toLowerCase().includes(pathLower)).join('\n');
                }
                if (groupId) {
                    const g = this.recallEvidenceTaskGroups.find((eg, i) => eg.groupId === groupId || `group-${i}` === groupId);
                    const paths = new Set((g?.tasks ?? []).map((t) => t.path).filter(Boolean));
                    if (paths.size === 0) return lines.join('\n');
                    return lines.filter((l) => Array.from(paths).some((p) => l.includes(p))).join('\n');
                }
                return lines.join('\n');
            }
            default:
                return '';
        }
    }

    /** Full memory as single text from structured sections (for keyword grep fallback). */
    private fullMemoryTextSupplier: Supplier<string> = refreshableMemoizeSupplier<string, number>(
        () => {
            const prompt = this.initialPrompt ?? '';
            const parts: string[] = ['[User]\n' + prompt];
            for (const stage of ANALYSIS_HISTORY_STAGES) {
                const text = this.getSectionText(stage, {});
                if (text.trim()) parts.push(`[${stage}]\n${text}`);
            }
            return parts.join('\n\n');
        },
        () =>
            this.verifiedPaths.size +
            this.recallDimensions.length +
            this.reconReports.length +
            (this.consolidatorOutput ? 1 : 0) +
            this.recallEvidenceTaskGroups.length +
            this.recallEvidencePacks.length,
        (a, b) => a !== b
    );

    /**
     * Parse query mini-language: id:XXX, stage:X, path:X, dimension:X, group:X, list (or empty = list).
     */
    private parseSearchQuery(
        query: string
    ): { id?: string; stage?: string; path?: string; dimension?: string; group?: string; list?: boolean; keyword?: string } {
        const q = (query ?? '').trim();
        const result: {
            id?: string;
            stage?: string;
            path?: string;
            dimension?: string;
            group?: string;
            list?: boolean;
            keyword?: string;
        } = {};
        if (!q || q.toLowerCase() === 'list') {
            result.list = true;
            return result;
        }
        let rest = q;
        const idMatch = rest.match(/\bid:(\S+)/i);
        if (idMatch) {
            result.id = idMatch[1].trim();
            rest = rest.replace(idMatch[0], '').trim();
        }
        const stageMatch = rest.match(/\bstage:(\S+)/i);
        if (stageMatch) {
            result.stage = stageMatch[1].trim();
            rest = rest.replace(stageMatch[0], '').trim();
        }
        const pathMatch = rest.match(/\bpath:(\S+)/i);
        if (pathMatch) {
            result.path = pathMatch[1].trim().replace(/^\[\[|\]\]$/g, '');
            rest = rest.replace(pathMatch[0], '').trim();
        }
        const dimMatch = rest.match(/\bdimension:(\S+)/i);
        if (dimMatch) {
            result.dimension = dimMatch[1].trim();
            rest = rest.replace(dimMatch[0], '').trim();
        }
        const groupMatch = rest.match(/\bgroup:(\S+)/i);
        if (groupMatch) {
            result.group = groupMatch[1].trim();
            rest = rest.replace(groupMatch[0], '').trim();
        }
        if (rest.length > 0) result.keyword = rest;
        return result;
    }

    /**
     * Search structured analysis by query: list (overview), stage:/path:/dimension:/group: (filter), or keyword (grep on full memory).
     */
    public searchHistory(query: string, options?: { maxChars?: number }): string {
        const maxChars = options?.maxChars ?? 4000;
        const parsed = this.parseSearchQuery(query);

        if (parsed.id) {
            return `id: is not supported. Use "list" for overview or "stage:Classify|Dimensions|Recon|Consolidator|EvidenceGroups|Evidence", "path:<path>", "dimension:<id>", "group:<id>", or keyword.`.slice(0, maxChars);
        }

        if (parsed.list) {
            const has = (stage: string) => this.getSectionText(stage, {}).trim().length > 0;
            const stageLines = ANALYSIS_HISTORY_STAGES.map((s) => `  ${s}: ${has(s) ? 'yes' : 'no'}`).join('\n');
            return `Analysis overview (query by stage/path/dimension/group or keyword)\nStages:\n${stageLines}\nUse: stage:<Classify|Dimensions|Recon|Consolidator|EvidenceGroups|Evidence>, path:<path>, dimension:<id>, group:<id>, or free text.`.slice(0, maxChars);
        }

        const filters = {
            path: parsed.path,
            dimension: parsed.dimension,
            group: parsed.group,
        };
        const stage = parsed.stage?.trim();
        let candidateText = '';

        if (stage && ANALYSIS_HISTORY_STAGES.includes(stage as (typeof ANALYSIS_HISTORY_STAGES)[number])) {
            candidateText = this.getSectionText(stage, filters);
        } else if (parsed.path || parsed.dimension || parsed.group) {
            const parts: string[] = [];
            for (const s of ANALYSIS_HISTORY_STAGES) {
                const t = this.getSectionText(s, filters);
                if (t.trim()) parts.push(`[${s}]\n${t}`);
            }
            candidateText = parts.join('\n\n');
        } else {
            candidateText = this.fullMemoryTextSupplier();
        }

        if (parsed.keyword) {
            const searchIn = candidateText.length > 0 ? candidateText : this.fullMemoryTextSupplier();
            const matches = this.grepInMemoryText(searchIn, parsed.keyword, { contextLines: 2, maxMatches: 15 });
            if (matches.length > 0) {
                return matches.map((m) => `Line ${m.line}:\n${m.text}`).join('\n---\n').slice(0, maxChars);
            }
            if (candidateText.trim()) return candidateText.slice(0, maxChars);
            return `No matches for "${parsed.keyword}". Use "list" to see available stages.`.slice(0, maxChars);
        }

        if (candidateText.trim()) return candidateText.slice(0, maxChars);
        return `No content for the query. Use "list" to see available stages (Classify, Dimensions, Recon, Consolidator, EvidenceGroups, Evidence).`.slice(0, maxChars);
    }

    /** Grep over full memory text (fallback when entry filter returns no hits). */
    private grepInMemoryText(
        fullText: string,
        query: string,
        options?: { caseSensitive?: boolean; maxMatches?: number; contextLines?: number }
    ): Array<{ line: number; text: string }> {
        const cap = Math.min(DEFAULT_GREP_MAX_MATCHES, options?.maxMatches ?? DEFAULT_GREP_MAX_MATCHES);
        const contextLines = options?.contextLines ?? 2;
        const { regex } = buildAutoRegex(query, options?.caseSensitive ?? false);
        const lines = fullText.split(/\r?\n/);
        const matches: Array<{ line: number; text: string }> = [];

        for (let i = 0; i < lines.length && matches.length < cap; i++) {
            const lineText = lines[i] ?? '';
            regex.lastIndex = 0;
            let guard = 0;
            let m: RegExpExecArray | null;
            while ((m = regex.exec(lineText)) !== null) {
                const start = Math.max(0, i - contextLines);
                const end = Math.min(lines.length, i + contextLines + 1);
                const context = lines.slice(start, end).join('\n');
                matches.push({ line: i + 1, text: context });
                if (matches.length >= cap) break;
                if (m[0]?.length === 0) {
                    regex.lastIndex = Math.min(lineText.length, regex.lastIndex + 1);
                }
                guard++;
                if (guard > 10_000) break;
            }
        }
        return matches;
    }
}