import { LLMRequestMessage, LLMStreamEvent, mergeTokenUsage, OneGenerationContext, StreamTriggerName, UIStepType } from '@/core/providers/types';
import { toReActThoughtPromptMessages, generateToolCallId, convertMessagesToText, getToolErrorMessage } from '@/core/providers/adapter/ai-sdk-adapter';
import { localWebSearchTool } from '@/service/tools/search-web';
import { Experimental_Agent as Agent, hasToolCall, stepCountIs } from 'ai';
import { PromptId } from '@/service/prompt/PromptId';
import { submitFinalAnswerTool } from '@/service/tools/submit-final-answer';
import { AgentTool, ManualToolCallHandler } from '@/service/tools/types';
import { buildToolCorrectionMessage, buildToolErrorStreamEvent } from '@/core/providers/helpers/message-helper';
import { AIServiceManager } from '../chat/service-manager';
import { RawSearchAgent } from './search-agent-helper/RawSearchAgent';
import { callAgentTool } from '../tools/call-agent-tool';
import { setCurrentAnalysisContext } from '@/core/analysis-context-holder';
import { getUpdateResultHandlersMap } from './search-agent-helper/helpers/DashboardUpdateToolBuilder';
import { AgentContextManager } from './search-agent-helper/AgentContextManager';
import { SummaryAgent } from './search-agent-helper/SummaryAgent';
import { DashboardUpdateAgent } from './search-agent-helper/DashboardUpdateAgent';
import { FinalRefineAgent } from './search-agent-helper/FinalRefineAgent';
import { MindFlowAgent, MindFlowPhase } from './search-agent-helper/MindFlowAgent';
import { DocSimpleAgent } from './search-agent-helper/DocSimpleAgent';
import { memoizeSupplier } from '@/core/utils/functions';
import { emptyUsage } from '@/core/providers/types';
import { generateUuidWithoutHyphens } from '@/core/utils/id-utils';
import { accumulateTokenUsage, buildPromptTraceDebugEvent } from '@/core/providers/helpers/stream-helper';

/** docSimple = current note only; vaultSimple = vault search then summarize; vaultFull = deep vault analysis. */
export type AnalysisMode = 'docSimple' | 'vaultSimple' | 'vaultFull';

export interface AISearchAgentOptions {
    enableWebSearch?: boolean;
    enableLocalSearch?: boolean;
    /** Required. docSimple | vaultSimple | vaultFull. Doc scope for docSimple uses stream(opts.scopeValue). */
    analysisMode: AnalysisMode;
    /**
     * Maximum wall clock time in milliseconds for the entire search.
     */
    maxWallClockMs?: number;
}

/**
 * Tool set for thought agent (coordinator).
 */
type ThoughtToolSet = {
    call_search_agent: AgentTool;
    submit_final_answer: AgentTool;
};

/** Agent loop config per analysis mode. */
interface AgentLoopConfig {
    maxMultiAgentIterations: number;
    maxWallClockMs: number;
}

function getAgentConfig(mode: AnalysisMode): AgentLoopConfig {
    switch (mode) {
        case 'docSimple':
            return {
                maxMultiAgentIterations: 1,
                maxWallClockMs: 5 * 60 * 1000,
            };
        case 'vaultSimple':
            return {
                maxMultiAgentIterations: 10,
                maxWallClockMs: 5 * 60 * 1000,
            };
        case 'vaultFull':
        default:
            return {
                maxMultiAgentIterations: 100,
                maxWallClockMs: 10 * 60 * 1000,
            };
    }
}

/** How to render the block content. Add new type in DashboardUpdateToolBuilder + DashboardBlocksSection. */
export type DashboardRenderEngine = 'MARKDOWN' | 'TILE' | 'ACTION_GROUP' | 'MERMAID';

/**
 * @deprecated
 */
export const RESULT_UPDATE_TOOL_NAMES = new Set(['update_sources', 'update_source_scores', 'update_topics', 'update_graph', 'add_dashboard_blocks']);

/** Single item in a TILE or ACTION_GROUP block. */
export interface DashboardBlockItem {
    id: string;
    title: string;
    description?: string;
    icon?: string;
    color?: string;
}

/** Dynamic dashboard block; AI decides title, weight, and content by renderEngine. */
export interface DashboardBlock {
    id: string;
    title?: string;
    /** 0-10; drives grid layout: 1-3 small, 4-6 medium, 7-10 full-width. */
    weight?: number;
    renderEngine: DashboardRenderEngine;
    items?: DashboardBlockItem[];
    markdown?: string;
    mermaidCode?: string;
}

export interface AISearchSource {
    id: string;
    title: string;
    // important: we will open file by this path.
    path: string;
    // why it was selected or rejected.
    reasoning: string;
    // add badges to the item to quickly judge the role of each note in the current analysis.
    badges: string[];
    score: {
        // 0~100
        physical: number;
        semantic: number;
        average: number;
    }
}

export interface AISearchTopic {
    label: string;
    weight: number;
    suggestQuestions?: string[];
}

export interface AISearchNode {
    // uuid of the node. generated by agent.
    id: string;
    // we can add many types of nodes. like file, folder, concept, tag, etc. determined by Agent.
    type: string;
    // title of the node. generated by agent.
    title: string;
    // important: we will open file by this path.
    path?: string;
    // attributes of the node. like tags, categories, etc. determined by Agent.
    attributes: {
        [key: string]: any;
    };
}

export interface AISearchEdge {
    // uuid of the edge. generated by agent.
    id: string;
    // uuid of the source node.
    source: string;
    // type of the edge. like link, reference, etc. determined by Agent.
    type: string;
    // uuid of the target node.
    target: string;
    // attributes of the edge. like weight, etc. determined by Agent.
    attributes: {
        [key: string]: any;
    };
}

/**
 * @deprecated
 */
export interface AISearchGraph {
    nodes: AISearchNode[];
    edges: AISearchEdge[];
}

export interface SearchAgentResult {
    /** Short display title (generated at end of analysis). */
    title?: string;
    summary: string;
    /**
     * @deprecated
     * */
    graph: AISearchGraph;
    dashboardBlocks?: DashboardBlock[];
    topics: AISearchTopic[];
    sources: AISearchSource[];
    /** Overview diagram generated by Mermaid Overview Agent (raw Mermaid code). */
    overviewMermaid?: string;
    /** Follow-up questions suggested by a dedicated agent from full search history/session; not from topics. */
    suggestedFollowUpQuestions?: string[];
}

/**
 * Search Agent.
 * ReAct architecture.
 * Multi agent architecture. (SubAgents)
 */
export class AISearchAgent {
    /** 
     * DocSimple: single-file Q&A agent. Created only when analysisMode === 'docSimple'. 
     * */
    private docSimpleAgent: DocSimpleAgent;

    /** 
     * MindFlow agent: thinking tree, progress, continue/stop decision 
     * */
    private mindFlowAgent: MindFlowAgent;
    /**
     * Thought Agent - main coordinator for ReAct loop
     */
    private thoughtAgent: Agent<ThoughtToolSet>;
    /**
     * Search Agent - sub agent for search tasks
     */
    private searchAgent: RawSearchAgent;

    /** 
     * Finish-phase agents 
     * */
    private summaryAgent: SummaryAgent;
    private finalRefineAgent: FinalRefineAgent;
    /** 
     * Dashboard update orchestrator: topics, sources, graph, blocks, review 
     * */
    private dashboardUpdateAgent: DashboardUpdateAgent;

    /**
     * Manual tool call handlers
     */
    private manualToolCallHandlers: Record<string, ManualToolCallHandler> = {};

    /**
     * Agent memory
     */
    private agentContextManager: AgentContextManager;

    /** Last thought-step context, so finish-phase (e.g. summary) can use its tool evidence when context is not passed. */
    private lastOneGenerationContext: OneGenerationContext | undefined;

    constructor(
        private readonly aiServiceManager: AIServiceManager,
        private options: AISearchAgentOptions,
    ) {
        this.docSimpleAgent = new DocSimpleAgent(this.aiServiceManager);

        this.agentContextManager = new AgentContextManager(this.aiServiceManager);

        const { provider: thoughtProvider, modelId: thoughtModel } = this.aiServiceManager.getModelForPrompt(PromptId.ThoughtAgent);
        const outputControl = this.aiServiceManager.getSettings()?.defaultOutputControl;
        const thoughtTemperature = outputControl?.temperature ?? 0.6;
        const thoughtMaxTokens = outputControl?.maxOutputTokens ?? 4096;
        this.thoughtAgent = new Agent<ThoughtToolSet>({
            model: this.aiServiceManager.getMultiChat()
                .getProviderService(thoughtProvider)
                .modelClient(thoughtModel),
            tools: {
                call_search_agent: callAgentTool('search'),
                submit_final_answer: submitFinalAnswerTool(),
            },
            stopWhen: [
                stepCountIs(1),
                hasToolCall('submit_final_answer'),
            ],
            temperature: thoughtTemperature,
            maxOutputTokens: thoughtMaxTokens,
        });

        this.searchAgent = new RawSearchAgent(
            this.aiServiceManager,
            { enableWebSearch: this.options.enableWebSearch, enableLocalSearch: this.options.enableLocalSearch },
            this.agentContextManager,
        );
        this.manualToolCallHandlers['call_search_agent'] = {
            toolName: 'call_search_agent',
            triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT,
            handle: this.searchAgent.manualToolCallHandle.bind(this.searchAgent),
            outputGetter: (resultCollector) => resultCollector.searchResultChunks,
        };

        const innerAgentCreateParams = {
            aiServiceManager: this.aiServiceManager,
            context: this.agentContextManager,
            rawSearchAgent: this.searchAgent,
            options: {
                enableWebSearch: this.options.enableWebSearch,
                enableLocalSearch: this.options.enableLocalSearch,
                analysisMode: this.options.analysisMode,
            },
        };
        this.mindFlowAgent = new MindFlowAgent(innerAgentCreateParams);
        this.summaryAgent = new SummaryAgent(innerAgentCreateParams);
        this.finalRefineAgent = new FinalRefineAgent(innerAgentCreateParams);
        this.dashboardUpdateAgent = new DashboardUpdateAgent(innerAgentCreateParams);
    }

    /**
     * Stream search results with ReAct loop (ThoughtAgent coordinates SearchAgent)
     * @param opts.scopeValue Used by DocSimpleAgent (current file path)
     */
    async stream(prompt: string, opts?: { scopeValue?: string }): Promise<AsyncGenerator<LLMStreamEvent>> {
        // Initialize agent memory for this session
        this.agentContextManager.resetAgentMemory(prompt);

        if (this.options.analysisMode === 'docSimple') {
            return this.docSimpleAgent!.stream(prompt, { scopeValue: opts?.scopeValue });
        }

        // vaultSimple vaultFull try to execute the loop.
        this.agentContextManager.resetAgentResult();
        this.mindFlowAgent.resetSessionState();
        setCurrentAnalysisContext({
            getResult: () => this.agentContextManager.getAgentResult(),
            getVerifiedPaths: () => this.agentContextManager.getVerifiedPaths(),
            getHandlers: (fieldName) => getUpdateResultHandlersMap()[fieldName],
        });
        return this.executeReActLoop();
    }

    /**
     * Search this session's chat history by query. Used by follow-up flows to look up analysis context.
     */
    searchHistory(query: string, options?: { maxChars?: number }): string {
        return this.agentContextManager.searchHistory(query, options);
    }

    /**
     * Execute the ReAct loop (ThoughtAgent coordinates SearchAgent)
     * Implements controlled state machine with early stop and time budget.
     */
    private async *executeReActLoop(): AsyncGenerator<LLMStreamEvent> {
        // iteration control
        const cfg = getAgentConfig(this.options.analysisMode);
        let iterationCount = 0;
        let reActStartTimeMs = Date.now();
        let isSubmitResultCalled = false;

        // Initial pre-thought: plan the first exploration step (only once before loop)
        yield* this.runMindFlowAgent('pre-thought');

        while (iterationCount < cfg.maxMultiAgentIterations) {
            iterationCount++;

            // Check time budget before starting new iteration
            const elapsedMs = Date.now() - reActStartTimeMs;
            if (elapsedMs > cfg.maxWallClockMs) {
                yield {
                    type: 'pk-debug',
                    debugName: 'thought-agent-time-budget-exceeded',
                    triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT,
                    extra: {
                        reason: `[AISearchAgent] Time budget exceeded (${elapsedMs}ms > ${cfg.maxWallClockMs}ms), forcing synthesis`,
                    },
                };
                break;
            }

            // run thought agent (wrapped in try-catch so one iteration error does not terminate entire AI Analysis)
            const oneGenerationContext: OneGenerationContext = {
                thoughtTextChunks: [],
                reasoningTextChunks: [],
                toolCalls: [],
                toolResults: [],
                stepTokenUsage: emptyUsage(),
            };
            const getThoughtText = memoizeSupplier(
                () => (oneGenerationContext.thoughtTextChunks ?? []).join('').trim(),
            );
            try {
                yield* this.runThoughtAgent(
                    oneGenerationContext,
                    () => { isSubmitResultCalled = true; },
                    getThoughtText,
                );
                // Build thought message and update agent memory
                const thoughtText = getThoughtText();
                this.agentContextManager.pushIterationThoughtMessage(
                    oneGenerationContext,
                    thoughtText ?? '',
                );
                this.lastOneGenerationContext = oneGenerationContext;

                yield* this.runMindFlowAgent('post-thought');

                // check if the result is good enough.
                let phaseResult: { shouldBreak: boolean } = { shouldBreak: false };
                yield {
                    type: 'ui-step',
                    uiType: UIStepType.STEPS_DISPLAY,
                    stepId: generateUuidWithoutHyphens(),
                    title: 'Evaluating progress...',
                    description: '',
                    triggerName: StreamTriggerName.SEARCH_COMPLETION_JUDGE,
                };
                const latestProgress = this.agentContextManager.getLatestMindflowProgress();
                yield* this.mindFlowAgent.checkMindFlowProgreeDecision(
                    iterationCount, latestProgress, (shouldBreak) => {
                        phaseResult.shouldBreak = shouldBreak;
                    }
                );
                if (phaseResult.shouldBreak) {
                    console.debug('[AISearchAgent] CompletionJudge decided to stop, end the loop');
                    break;
                }
            } catch (err) {
                const message = err instanceof Error ? err.message : String(err);
                console.error('[AISearchAgent] Thought agent iteration error (continuing next iteration):', err);
                yield {
                    type: 'pk-debug',
                    debugName: 'thought-agent-iteration-error',
                    triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT,
                    extra: {
                        reason: `[AISearchAgent] Thought agent error: ${message}. Continuing next iteration.`,
                        error: message,
                    },
                };
                continue;
            }

            // ThoughtAgent decided to submit final answer, end the loop
            if (isSubmitResultCalled) {
                console.debug('[AISearchAgent] ThoughtAgent decided to submit final answer, end the loop');
                break;
            }
        }

        if (!isSubmitResultCalled) {
            yield {
                type: 'pk-debug',
                debugName: 'Exited_loop_without_submitting',
                extra: {
                    messages: 'Exited loop without submitting (max iterations or early stop)',
                    reActStartTimeMs,
                    reActEndTimeMs: Date.now(),
                    reActDurationMs: Date.now() - reActStartTimeMs,
                },
            }
        }

        yield* this.finishReActLoop(reActStartTimeMs);
    }

    private async *runMindFlowAgent(
        phase: MindFlowPhase,
    ): AsyncGenerator<LLMStreamEvent> {
        if (this.options.analysisMode !== 'vaultFull') {
            return;
        }

        const mfStepId = generateUuidWithoutHyphens();
        yield {
            type: 'ui-step',
            uiType: UIStepType.STEPS_DISPLAY,
            stepId: mfStepId,
            title: phase === 'pre-thought' ? 'Planning next exploration...' : 'Reflecting on findings...',
            description: '',
            triggerName: StreamTriggerName.SEARCH_MINDFLOW_AGENT,
        };
        for await (const ev of this.mindFlowAgent.stream({ stepId: mfStepId, phase })) {
            accumulateTokenUsage(ev, (usage) => this.agentContextManager.accumulateTokenUsage(usage));
            yield ev;
        }
    }

    private async *runThoughtAgent(
        oneGenerationContext: OneGenerationContext,
        setSubmitResultCalled: (called: boolean) => void,
        getThoughtText: () => string,
    ): AsyncGenerator<LLMStreamEvent> {
        const stepId = generateUuidWithoutHyphens();
        yield {
            type: 'ui-step',
            uiType: UIStepType.STEPS_DISPLAY,
            stepId,
            title: 'Thinking about your request...',
            description: 'Thinking',
            triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT,
        };

        // user prompt
        let currentPromptHolder: any[] = [];
        for await (const chunk of this.agentContextManager.buildCurrentPrompt((prompt: LLMRequestMessage[]) => {
            currentPromptHolder.push(prompt);
        })) {
            yield chunk;
        }
        // Get the final prompt after summarization is complete
        const currentPrompt = currentPromptHolder[0] as LLMRequestMessage[];
        const nextThoughtPrompt = toReActThoughtPromptMessages(currentPrompt);
        oneGenerationContext.userPrompt = convertMessagesToText(currentPrompt ?? []);
        // system prompt
        const systemPrompt = await this.aiServiceManager.renderPrompt(PromptId.ThoughtAgent, {
            analysisMode: this.options.analysisMode,
            simpleMode: this.options.analysisMode === 'vaultSimple'
        });
        oneGenerationContext.systemPrompt = systemPrompt;
        // call agent
        const thoughtStream = this.thoughtAgent.stream({
            system: systemPrompt,
            prompt: nextThoughtPrompt,
        });

        yield buildPromptTraceDebugEvent(StreamTriggerName.SEARCH_THOUGHT_AGENT, systemPrompt, oneGenerationContext.userPrompt);
        // Process thoughtAgent's stream in real-time
        for await (const chunk of thoughtStream.fullStream) {
            switch (chunk.type) {
                case 'text-start':
                    yield {
                        type: 'ui-step',
                        uiType: UIStepType.STEPS_DISPLAY,
                        stepId,
                        title: 'Thinking about your request... Thinking...',
                        description: 'Start to think about the request...',
                        triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT,
                    };
                    break;
                case 'text-delta':
                    oneGenerationContext.thoughtTextChunks.push(chunk.text);
                    yield { type: 'text-delta', text: chunk.text, triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT };
                    yield {
                        type: 'ui-step-delta',
                        uiType: UIStepType.STEPS_DISPLAY,
                        stepId,
                        descriptionDelta: chunk.text,
                        triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT,
                    };
                    break;
                case 'reasoning-start':
                    yield {
                        type: 'ui-step',
                        uiType: UIStepType.STEPS_DISPLAY,
                        stepId,
                        title: 'Thinking about your request... Reasoning...',
                        description: 'Start to reason about the request...',
                        triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT,
                    };
                    break;
                case 'reasoning-delta':
                    oneGenerationContext.reasoningTextChunks.push(chunk.text);
                    yield { type: 'reasoning-delta', text: chunk.text, triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT };
                    yield {
                        type: 'ui-step-delta',
                        uiType: UIStepType.STEPS_DISPLAY,
                        stepId,
                        descriptionDelta: chunk.text,
                        triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT,
                    };
                    break;
                case 'tool-call': {
                    const toolCallId = (chunk as { toolCallId?: string }).toolCallId ?? generateToolCallId();
                    oneGenerationContext.toolCalls.push({ toolCallId, toolName: chunk.toolName, input: chunk.input });
                    if (chunk.toolName === 'submit_final_answer') {
                        setSubmitResultCalled(true);
                    }
                    yield {
                        type: 'tool-call',
                        id: toolCallId,
                        toolName: chunk.toolName,
                        input: chunk.input,
                        triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT,
                    };

                    const manualToolCallHandler = this.manualToolCallHandlers[chunk.toolName];
                    if (manualToolCallHandler) {
                        const resultCollector: Record<string, any> = {};
                        yield* manualToolCallHandler.handle(chunk.input, resultCollector);
                        oneGenerationContext.stepTokenUsage = mergeTokenUsage(oneGenerationContext.stepTokenUsage, resultCollector.stepTokenUsage);
                        oneGenerationContext.toolResults.push({
                            toolCallId,
                            toolName: chunk.toolName,
                            output: {
                                type: 'text',
                                value: JSON.stringify(manualToolCallHandler.outputGetter?.(resultCollector) ?? resultCollector),
                            }
                        });
                        yield {
                            type: 'tool-result',
                            id: toolCallId,
                            toolName: chunk.toolName,
                            input: chunk.input,
                            output: manualToolCallHandler.outputGetter?.(resultCollector) ?? resultCollector,
                            triggerName: manualToolCallHandler.triggerName,
                        };
                    }
                    break;
                }
                case 'tool-result':
                    // already handled by manual tool call handler.
                    if (this.manualToolCallHandlers[chunk.toolName]) {
                        break;
                    }

                    const toolCallId = (chunk as { toolCallId?: string }).toolCallId ?? generateToolCallId();
                    oneGenerationContext.toolResults.push({
                        toolCallId,
                        toolName: chunk.toolName,
                        output: {
                            type: 'text',
                            value: JSON.stringify(chunk.output),
                        }
                    });
                    yield {
                        type: 'tool-result',
                        id: toolCallId,
                        toolName: chunk.toolName,
                        input: chunk.input,
                        output: chunk.output,
                        triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT,
                        extra: {
                            currentResult: this.agentContextManager.getAgentResult(),
                        },
                    };
                    break;
                case 'finish':
                    oneGenerationContext.stepTokenUsage = mergeTokenUsage(oneGenerationContext.stepTokenUsage, chunk.totalUsage);
                    yield {
                        type: 'on-step-finish',
                        text: getThoughtText(),
                        finishReason: chunk.finishReason,
                        usage: chunk.totalUsage,
                        triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT
                    };
                    break;
                case 'tool-error': {
                    const errMsg = getToolErrorMessage(chunk);
                    const toolName = (chunk as any).toolName ?? 'unknown';

                    // All errors must be yield as error.
                    yield buildToolErrorStreamEvent(toolName, errMsg, chunk, StreamTriggerName.SEARCH_THOUGHT_AGENT);

                    // try to inject corrective reminder into agent memory for next iteration
                    this.agentContextManager.pushIterationErrorMessage(
                        buildToolCorrectionMessage(toolName, errMsg)
                    );
                    break;
                }
                case 'start':
                case 'start-step':
                case 'reasoning-end':
                case 'text-end':
                case 'finish-step':
                case 'tool-input-start':
                case 'tool-input-delta':
                case 'tool-input-end':
                    // devtools will merge these duplicate logs.
                    console.debug('[AISearchAgent] thoughtAgent skip. one of the following types: '
                        + 'start, start-step, reasoning-start, reasoning-end, text-start, text-end, '
                        + 'finish-step, tool-input-start, tool-input-delta, tool-input-end');
                    break;
                default:
                    yield { type: 'unSupported', chunk: chunk, comeFrom: 'thoughtAgent', triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT };
                    break;
            }
        }

        // the graph has already been changed to be a mind flow display not sources relationship.
        // Deterministic streaming write: new verified paths -> placeholder source + single-node graph patch.
        console.debug('[AISearchAgent] emitStreamingSourcesFromVerifiedPaths');
        for await (const ev of this.dashboardUpdateAgent.emitStreamingSourcesFromVerifiedPaths()) {
            yield ev;
        }
        console.debug('[AISearchAgent] emitStreamingSourcesFromVerifiedPaths done');
    }

    private async *finishReActLoop(reActStartTimeMs: number): AsyncGenerator<LLMStreamEvent> {
        for await (const ev of this.finishReActLoopInternal(reActStartTimeMs)) {
            accumulateTokenUsage(ev, (usage) => this.agentContextManager.accumulateTokenUsage(usage));
            yield ev;
        }
    }

    private async *finishReActLoopInternal(reActStartTimeMs: number): AsyncGenerator<LLMStreamEvent> {
        // all thought finish. trigger prompt gen once. and later we can use the cached prompt.
        yield* this.agentContextManager.buildCurrentPrompt();

        switch (this.options.analysisMode) {
            case 'vaultSimple':
                yield* this.streamSimpleAnalysis();
                break;
            case 'vaultFull':
                yield* this.streamFullAnalysis();
                break;
            default:
                yield {
                    type: 'error',
                    error: new Error('Analysis mode not supported'),
                    triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT,
                    extra: {
                        analysisMode: this.options.analysisMode,
                    },
                }
                break;
        }

        yield {
            type: 'complete',
            finishReason: 'stop',
            usage: this.agentContextManager.getAgentMemory().totalTokenUsage,
            durationMs: Date.now() - reActStartTimeMs,
            result: this.agentContextManager.getAgentResult(),
            triggerName: StreamTriggerName.SEARCH_THOUGHT_AGENT,
        };
    }

    private async *streamSimpleAnalysis(): AsyncGenerator<LLMStreamEvent> {
        // Simple refine for non-vaultFull modes
        yield* this.finalRefineAgent.streamSourcesRefine();

        yield* this.summaryAgent.streamMultiStep({
            streamTitle: true,
            streamSummary: true,
            streamMermaidOverview: false,
        });
    }

    private async *streamFullAnalysis(): AsyncGenerator<LLMStreamEvent> {
        yield* this.finalRefineAgent.streamSourcesRefine();

        yield* this.dashboardUpdateAgent.runDashboardUpdate();

        yield* this.summaryAgent.streamMultiStep({
            streamTitle: true,
            streamSummary: true,
            streamMermaidOverview: true,
        });
    }

}
