import { LLMStreamEvent, StreamTriggerName } from '@/core/providers/types';
import { AIServiceManager } from '../chat/service-manager';
import { setCurrentAnalysisContext } from '@/core/analysis-context-holder';
import { getUpdateResultHandlersMap } from './search-agent-helper/helpers/DashboardUpdateToolBuilder';
import { AgentContextManager } from './search-agent-helper/AgentContextManager';
import { SummaryAgent } from './search-agent-helper/SummaryAgent';
import { DashboardAgent } from './search-agent-helper/DashboardAgent';
import { FinalRefineAgent } from './search-agent-helper/FinalRefineAgent';
import { SlotRecallAgent } from './search-agent-helper/SlotRecallAgent';
import { DocSimpleAgent } from './search-agent-helper/DocSimpleAgent';
import { accumulateTokenUsage } from '@/core/providers/helpers/stream-helper';
import { ReportAgent } from './search-agent-helper/ReportAgent';
import type { ReportPlan, ReportVisualBlueprint } from '@/core/schemas/agents/search-agent-schemas';
import { generateUuidWithoutHyphens } from '@/core/utils/id-utils';
import { uiStageSignal, uiStepStart } from './search-agent-helper/helpers/search-ui-events';

/** docSimple = current note only; vaultSimple = vault search then summarize; vaultFull = deep vault analysis. */
export type AnalysisMode = 'docSimple' | 'vaultSimple' | 'vaultFull';

export interface AISearchAgentOptions {
    enableWebSearch?: boolean;
    enableLocalSearch?: boolean;
    /** Required. docSimple | vaultSimple | vaultFull. Doc scope for docSimple uses stream(opts.scopeValue). */
    analysisMode: AnalysisMode;
    /**
     * Maximum wall clock time in milliseconds for the entire search.
     */
    maxWallClockMs?: number;
}

/** How to render the block content. Add new type in DashboardUpdateToolBuilder + DashboardBlocksSection. */
export type DashboardRenderEngine = 'MARKDOWN' | 'TILE' | 'ACTION_GROUP' | 'MERMAID';

/** Single item in a TILE or ACTION_GROUP block. */
export interface DashboardBlockItem {
    id: string;
    title: string;
    description?: string;
    icon?: string;
    color?: string;
}

/** Dynamic dashboard block; AI decides title, weight, and content by renderEngine. */
export interface DashboardBlock {
    id: string;
    title?: string;
    /** 0-10; drives grid layout: 1-3 small, 4-6 medium, 7-10 full-width. */
    weight?: number;
    renderEngine: DashboardRenderEngine;
    items?: DashboardBlockItem[];
    markdown?: string;
    mermaidCode?: string;
}

export interface AISearchSource {
    id: string;
    title: string;
    // important: we will open file by this path.
    path: string;
    // why it was selected or rejected.
    reasoning: string;
    // add badges to the item to quickly judge the role of each note in the current analysis.
    badges: string[];
    score: {
        // 0~100
        physical: number;
        semantic: number;
        average: number;
    }
}

export interface AISearchTopic {
    label: string;
    weight: number;
    suggestQuestions?: string[];
}

export interface AISearchNode {
    // uuid of the node. generated by agent.
    id: string;
    // we can add many types of nodes. like file, folder, concept, tag, etc. determined by Agent.
    type: string;
    // title of the node. generated by agent.
    title: string;
    // important: we will open file by this path.
    path?: string;
    // attributes of the node. like tags, categories, etc. determined by Agent.
    attributes: {
        [key: string]: any;
    };
}

export interface AISearchEdge {
    // uuid of the edge. generated by agent.
    id: string;
    // uuid of the source node.
    source: string;
    // type of the edge. like link, reference, etc. determined by Agent.
    type: string;
    // uuid of the target node.
    target: string;
    // attributes of the edge. like weight, etc. determined by Agent.
    attributes: {
        [key: string]: any;
    };
}

/**
 * @deprecated
 */
export interface AISearchGraph {
    nodes: AISearchNode[];
    edges: AISearchEdge[];
}

export interface SearchAgentResult {
    /** Short display title (generated at end of analysis). */
    title?: string;
    summary: string;
    dashboardBlocks?: DashboardBlock[];
    topics: AISearchTopic[];
    sources: AISearchSource[];
    /** Overview diagram generated by Mermaid Overview Agent (raw Mermaid code). */
    evidenceMermaidOverviewAgent?: string;
    /** Follow-up questions suggested by a dedicated agent from full search history/session; not from topics. */
    suggestedFollowUpQuestions?: string[];
    /** Executable report outline from ReportPlanAgent (body/appendices/actions/sources specs). */
    reportPlan?: ReportPlan;
    /** Per-block visual prescriptions from VisualBlueprintAgent (after report plan). */
    reportVisualBlueprint?: ReportVisualBlueprint;
}

/**
 * Search Agent. Slot-based pipeline for vault: SlotRecallAgent (classify → recall) then finish agents (FinalRefine, Summary, Dashboard).
 */
export class AISearchAgent {
    /** DocSimple: single-file Q&A agent when analysisMode === 'docSimple'. */
    private docSimpleAgent: DocSimpleAgent;

    /** Slot-based recall pipeline: classify → strategy → parallel recall → slot UI. */
    private slotRecallAgent: SlotRecallAgent;

    private reportAgent: ReportAgent;
    /** 
     * Finish-phase agents 
     * */
    private summaryAgent: SummaryAgent;
    private finalRefineAgent: FinalRefineAgent;
    /** 
     * Dashboard update orchestrator: topics, sources, graph, blocks, review 
     * */
    private dashboardUpdateAgent: DashboardAgent;

    /**
     * Agent memory
     */
    private agentContextManager: AgentContextManager;

    constructor(
        private readonly aiServiceManager: AIServiceManager,
        private options: AISearchAgentOptions,
    ) {
        this.docSimpleAgent = new DocSimpleAgent(this.aiServiceManager);

        this.agentContextManager = new AgentContextManager(this.aiServiceManager);

        const innerAgentCreateParams = {
            aiServiceManager: this.aiServiceManager,
            context: this.agentContextManager,
            options: {
                enableWebSearch: this.options.enableWebSearch,
                enableLocalSearch: this.options.enableLocalSearch,
                analysisMode: this.options.analysisMode,
            },
        };
        this.slotRecallAgent = new SlotRecallAgent(this.aiServiceManager, this.agentContextManager);

        this.summaryAgent = new SummaryAgent(innerAgentCreateParams);
        this.finalRefineAgent = new FinalRefineAgent(innerAgentCreateParams);
        this.dashboardUpdateAgent = new DashboardAgent(innerAgentCreateParams);
        this.reportAgent = new ReportAgent(this.aiServiceManager, this.agentContextManager);
    }

    /**
     * Stream search results. DocSimple: single-file Q&A; vault: SlotRecallAgent then finish agents.
     * @param opts.scopeValue Used by DocSimpleAgent (current file path)
     */
    async stream(prompt: string, opts?: { scopeValue?: string }): Promise<AsyncGenerator<LLMStreamEvent>> {
        // Initialize agent memory for this session
        this.agentContextManager.resetAgentMemory(prompt);

        if (this.options.analysisMode === 'docSimple') {
            return this.docSimpleAgent!.stream(prompt, { scopeValue: opts?.scopeValue });
        }

        setCurrentAnalysisContext({
            getResult: () => this.agentContextManager.getAgentResult(),
            getVerifiedPaths: () => this.agentContextManager.getVerifiedPaths(),
            getHandlers: (fieldName) => getUpdateResultHandlersMap()[fieldName],
        });
        return this.executeSlotPipeline();
    }

    /** Exposed for debug mount (e.g. window.__peakSearchDebug.getSnapshot). */
    public getContextManager(): AgentContextManager {
        return this.agentContextManager;
    }

    /**
     * Search this session's chat history by query. Used by follow-up flows to look up analysis context.
     */
    searchHistory(query: string, options?: { maxChars?: number }): string {
        return this.agentContextManager.searchHistory(query, options);
    }

    /**
     * Slot-based pipeline: SlotRecallAgent (classify → recall → slot UI) → streaming sources → finish agents.
     */
    private async *executeSlotPipeline(): AsyncGenerator<LLMStreamEvent> {
        const pipelineStartMs = Date.now();
        const runStepId = generateUuidWithoutHyphens();

        yield uiStepStart(
            { runStepId, stage: 'recall', agent: 'AISearchAgent' },
            { title: 'Starting analysis…', triggerName: StreamTriggerName.SEARCH_AI_AGENT }
        );
        yield uiStageSignal(
            { runStepId, stage: 'recall', agent: 'AISearchAgent' },
            { status: 'start', triggerName: StreamTriggerName.SEARCH_AI_AGENT }
        );

        try {
            for await (const ev of this.slotRecallAgent.stream({ runStepId })) {
                accumulateTokenUsage(ev, (usage) => this.agentContextManager.accumulateTokenUsage(usage));
                yield ev;
            }
        } catch (err) {
            yield uiStageSignal(
                { runStepId, stage: 'recall', agent: 'AISearchAgent' },
                { status: 'error', payload: { error: err instanceof Error ? err.message : String(err) }, triggerName: StreamTriggerName.SEARCH_AI_AGENT }
            );
            throw err;
        }
        yield uiStageSignal(
            { runStepId, stage: 'recall', agent: 'AISearchAgent' },
            { status: 'complete', triggerName: StreamTriggerName.SEARCH_AI_AGENT }
        );

        yield uiStepStart(
            { runStepId, stage: 'sourcesStreaming', agent: 'AISearchAgent' },
            { title: 'Streaming sources…', triggerName: StreamTriggerName.SEARCH_AI_AGENT }
        );
        yield uiStageSignal(
            { runStepId, stage: 'sourcesStreaming', agent: 'AISearchAgent' },
            { status: 'start', triggerName: StreamTriggerName.SEARCH_AI_AGENT }
        );
        for await (const ev of this.dashboardUpdateAgent.emitStreamingSourcesFromVerifiedPaths(StreamTriggerName.SEARCH_AI_AGENT)) {
            yield ev;
        }
        yield uiStageSignal(
            { runStepId, stage: 'sourcesStreaming', agent: 'AISearchAgent' },
            { status: 'complete', triggerName: StreamTriggerName.SEARCH_AI_AGENT }
        );

        yield uiStepStart(
            { runStepId, stage: 'report', agent: 'AISearchAgent' },
            { title: 'Generating report…', triggerName: StreamTriggerName.SEARCH_AI_AGENT }
        );
        yield uiStageSignal(
            { runStepId, stage: 'report', agent: 'AISearchAgent' },
            { status: 'start', triggerName: StreamTriggerName.SEARCH_AI_AGENT }
        );
        try {
            for await (const ev of this.reportAgent.streamReport({ analysisMode: this.options.analysisMode, runStepId })) {
                accumulateTokenUsage(ev, (usage) => this.agentContextManager.accumulateTokenUsage(usage));
                yield ev;
            }
        } catch (err) {
            yield uiStageSignal(
                { runStepId, stage: 'report', agent: 'AISearchAgent' },
                { status: 'error', payload: { error: err instanceof Error ? err.message : String(err) }, triggerName: StreamTriggerName.SEARCH_AI_AGENT }
            );
            throw err;
        }
        yield uiStageSignal(
            { runStepId, stage: 'report', agent: 'AISearchAgent' },
            { status: 'complete', triggerName: StreamTriggerName.SEARCH_AI_AGENT }
        );

        for await (const ev of this.dashboardUpdateAgent.emitStreamingSourcesFromVerifiedPaths()) {
            yield ev;
        }

        yield {
            type: 'complete',
            finishReason: 'stop',
            usage: this.agentContextManager.getTotalTokenUsage(),
            durationMs: Date.now() - pipelineStartMs,
            result: this.agentContextManager.getAgentResult(),
            triggerName: StreamTriggerName.SEARCH_AI_AGENT,
        };
    }

}
