/**
 * Shared types for the search agent pipeline.
 * These are the stable output types used by both the old (AISearchAgent) and new (VaultSearchAgent) pipelines,
 * and consumed by UI components, storage, and other services.
 */

/** How to render the block content. */
export type DashboardRenderEngine = 'MARKDOWN' | 'TILE' | 'ACTION_GROUP' | 'MERMAID';

/** Single item in a TILE or ACTION_GROUP block. */
export interface DashboardBlockItem {
	id: string;
	title: string;
	description?: string;
	icon?: string;
	color?: string;
}

/** Dynamic dashboard block; AI decides title, weight, and content by renderEngine. */
export interface DashboardBlock {
	id: string;
	title?: string;
	/** 0-10; drives grid layout: 1-3 small, 4-6 medium, 7-10 full-width. */
	weight?: number;
	renderEngine: DashboardRenderEngine;
	items?: DashboardBlockItem[];
	markdown?: string;
	mermaidCode?: string;
}

export interface AISearchSource {
	id: string;
	title: string;
	/** Important: we will open file by this path. */
	path: string;
	/** Why it was selected or rejected. */
	reasoning: string;
	/** Badges to quickly judge the role of each note in the current analysis. */
	badges: string[];
	score: {
		/** 0~100 */
		physical: number;
		semantic: number;
		average: number;
	};
}

export interface AISearchTopic {
	label: string;
	weight: number;
	suggestQuestions?: string[];
}

export interface AISearchNode {
	/** UUID of the node. Generated by agent. */
	id: string;
	/** Type of node: file, folder, concept, tag, etc. Determined by Agent. */
	type: string;
	/** Title of the node. Generated by agent. */
	title: string;
	/** Important: we will open file by this path. */
	path?: string;
	/** Attributes of the node: tags, categories, etc. Determined by Agent. */
	attributes: {
		[key: string]: any;
	};
}

export interface AISearchEdge {
	/** UUID of the edge. Generated by agent. */
	id: string;
	/** UUID of the source node. */
	source: string;
	/** Type of the edge: link, reference, etc. Determined by Agent. */
	type: string;
	/** UUID of the target node. */
	target: string;
	/** Attributes of the edge: weight, etc. Determined by Agent. */
	attributes: {
		[key: string]: any;
	};
}

/**
 * @deprecated Use GraphVisualization component directly; graph is built from sources + edges.
 */
export interface AISearchGraph {
	nodes: AISearchNode[];
	edges: AISearchEdge[];
}

/** vaultFull = deep vault analysis; aiGraph = multi-lens graph visualization. */
export type AnalysisMode = 'vaultFull' | 'aiGraph';

/** Evidence index by path: summaries and facts (claim + quote) for Evidence view in Sources. */
export type EvidenceIndex = Record<string, {
	summaries: string[];
	facts: Array<{ claim: string; quote: string; groupId?: string }>;
}>;

export interface SearchAgentResult {
	/** Short display title (generated at end of analysis). */
	title?: string;
	summary: string;
	dashboardBlocks?: DashboardBlock[];
	topics: AISearchTopic[];
	sources: AISearchSource[];
	/** Overview diagram generated by Mermaid Overview Agent (raw Mermaid code). */
	evidenceMermaidOverviewAgent?: string;
	/** Follow-up questions suggested by a dedicated agent from full search history/session. */
	suggestedFollowUpQuestions?: string[];
	/** Executable report outline from ReportPlanAgent. */
	reportPlan?: import('@/core/schemas/agents/search-agent-schemas').ReportPlan;
	/** Per-block visual prescriptions from VisualBlueprintAgent. */
	reportVisualBlueprint?: import('@/core/schemas/agents/search-agent-schemas').ReportVisualBlueprint;
	/** Evidence by path for Sources Evidence view. */
	evidenceIndex?: EvidenceIndex;
}
